In [361]:
from tkinter import *
import numpy as np
import pandas as pd
import os

In [362]:
l1=['back_pain','constipation','abdominal_pain','diarrhoea','mild_fever','yellow_urine',
    'yellowing_of_eyes','acute_liver_failure','fluid_overload','swelling_of_stomach',
    'swelled_lymph_nodes','malaise','blurred_and_distorted_vision','phlegm','throat_irritation',
    'redness_of_eyes','sinus_pressure','runny_nose','congestion','chest_pain','weakness_in_limbs',
    'fast_heart_rate','pain_during_bowel_movements','pain_in_anal_region','bloody_stool',
    'irritation_in_anus','neck_pain','dizziness','cramps','bruising','obesity','swollen_legs',
    'swollen_blood_vessels','puffy_face_and_eyes','enlarged_thyroid','brittle_nails',
    'swollen_extremeties','excessive_hunger','extra_marital_contacts','drying_and_tingling_lips',
    'slurred_speech','knee_pain','hip_joint_pain','muscle_weakness','stiff_neck','swelling_joints',
    'movement_stiffness','spinning_movements','loss_of_balance','unsteadiness',
    'weakness_of_one_body_side','loss_of_smell','bladder_discomfort','foul_smell_of urine',
    'continuous_feel_of_urine','passage_of_gases','internal_itching','toxic_look_(typhos)',
    'depression','irritability','muscle_pain','altered_sensorium','red_spots_over_body','belly_pain',
    'abnormal_menstruation','dischromic _patches','watering_from_eyes','increased_appetite','polyuria','family_history','mucoid_sputum',
    'rusty_sputum','lack_of_concentration','visual_disturbances','receiving_blood_transfusion',
    'receiving_unsterile_injections','coma','stomach_bleeding','distention_of_abdomen',
    'history_of_alcohol_consumption','fluid_overload','blood_in_sputum','prominent_veins_on_calf',
    'palpitations','painful_walking','pus_filled_pimples','blackheads','scurring','skin_peeling',
    'silver_like_dusting','small_dents_in_nails','inflammatory_nails','blister','red_sore_around_nose',
    'yellow_crust_ooze']

In [363]:
disease=['Fungal infection','Allergy','GERD','Chronic cholestasis','Drug Reaction',
    'Peptic ulcer diseae','AIDS','Diabetes','Gastroenteritis','Bronchial Asthma','Hypertension',
    ' Migraine','Cervical spondylosis',
    'Paralysis (brain hemorrhage)','Jaundice','Malaria','Chicken pox','Dengue','Typhoid','hepatitis A',
    'Hepatitis B','Hepatitis C','Hepatitis D','Hepatitis E','Alcoholic hepatitis','Tuberculosis',
    'Common Cold','Pneumonia','Dimorphic hemmorhoids(piles)',
    'Heartattack','Varicoseveins','Hypothyroidism','Hyperthyroidism','Hypoglycemia','Osteoarthristis',
    'Arthritis','(vertigo) Paroymsal  Positional Vertigo','Acne','Urinary tract infection','Psoriasis',
    'Impetigo']

In [364]:
l2=[]
for i in range(0,len(l1)):
    l2.append(0)
print(l2)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [365]:
df=pd.read_csv("training.csv")

In [366]:
df.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
    'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
    'Migraine':11,'Cervical spondylosis':12,
    'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
    'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
    'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
    'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
    '(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
    'Impetigo':40}},inplace=True)

In [367]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze  prognosis  
0                  0          0  
1                  0          0  
2                  0          0  
3                  0          0  
4                  0          0  

[5 rows x 133 columns]

In [368]:
df.tail()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze  prognosis  
4915                  0         36  
4916                  0         37  
4917                  0         38  
4918                  0         39  
4919                  1         40  

[5 rows x 133 columns]

In [369]:
df.isnull().values.any()

False

In [370]:
df.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...   blackheads     scurring  skin_peeling  \
count       4920.000000  ...  4920.000000  4920.000000   4920.000000   
mean           0.021951  ...     0.021951     0.021951      0.023171   
std            0.146539  ...     0.146539     0.146539      0.150461   
min            0.000000  ...     0.000000     0.000000      0.000000   
25%            0.000000  ...     0.000000     0.000000      0.000000   
50%            0.000000  ...     0.000000     0.000000      0.000000   
75%            0.000000  ...     0.000000     0.000000      0.000000   
max            1.000000  ...     1.000000     1.000000      1.000000   

       silver_like_dusting  small_dents_in_nails  inflammatory_nails  \
count          4920.000000           4920.000000         4920.000000   
mean              0.023171              0.023171            0.023171   
std               0.150461              0.150461            0.150461   
min               0.000000              0.000000            0.000000   
25%               0.000000              0.000000            0.000000   
50%               0.000000              0.000000            0.000000   
75%               0.000000              0.000000            0.000000   
max               1.000000              1.000000            1.000000   

           blister  red_sore_around_nose  yellow_crust_ooze    prognosis  
count  4920.000000           4920.000000        4920.000000  4920.000000  
mean      0.023171              0.023171           0.023171    20.000000  
std       0.150461              0.150461           0.150461    11.833362  
min       0.000000              0.000000           0.000000     0.000000  
25%       0.000000              0.000000           0.000000    10.000000  
50%       0.000000              0.000000           0.000000    20.000000  
75%       0.000000              0.000000           0.000000    30.000000  
max       1.000000              1.000000           1.000000    40.000000  

[8 rows x 133 columns]

In [371]:
x=df.iloc[:,:-1].values  
print(x)

[[1 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 1 1 1]]


In [372]:
df.shape

(4920, 133)

In [373]:
df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [374]:
X= df[l1]
y = df[["prognosis"]]
np.ravel(y)
print(X)
print(y)

      back_pain  constipation  abdominal_pain  diarrhoea  mild_fever  \
0             0             0               0          0           0   
1             0             0               0          0           0   
2             0             0               0          0           0   
3             0             0               0          0           0   
4             0             0               0          0           0   
...         ...           ...             ...        ...         ...   
4915          0             0               0          0           0   
4916          0             0               0          0           0   
4917          0             0               0          0           0   
4918          0             0               0          0           0   
4919          0             0               0          0           0   

      yellow_urine  yellowing_of_eyes  acute_liver_failure  fluid_overload  \
0                0                  0                    

In [375]:
tr=pd.read_csv("testing.csv")

In [376]:
tr.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
    'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
    'Migraine':11,'Cervical spondylosis':12,
    'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
    'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
    'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
    'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
    '(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
    'Impetigo':40}},inplace=True)


In [377]:
tr.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   
3        1          0                     0                    0          0   
4        1          1                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   
3       0           0             0        0                 0  ...   
4       0           0             1        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze  prognosis  
0                  0          0  
1                  0          1  
2                  0          2  
3                  0          3  
4                  0          4  

[5 rows x 133 columns]

In [378]:
tr.tail()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
36        0          0                     0                    0          0   
37        0          1                     0                    0          0   
38        0          0                     0                    0          0   
39        0          1                     0                    0          0   
40        0          1                     0                    0          0   

    chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
36       0           0             0        0                 0  ...   
37       0           0             0        0                 0  ...   
38       0           0             0        0                 0  ...   
39       0           1             0        0                 0  ...   
40       0           0             0        0                 0  ...   

    blackheads  scurring  skin_peeling  silver_like_dusting  \
36           0         0             0                    0   
37           1         1             0                    0   
38           0         0             0                    0   
39           0         0             1                    1   
40           0         0             0                    0   

    small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
36                     0                   0        0                     0   
37                     0                   0        0                     0   
38                     0                   0        0                     0   
39                     1                   1        0                     0   
40                     0                   0        1                     1   

    yellow_crust_ooze  prognosis  
36                  0         36  
37                  0         37  
38                  0         38  
39                  0         39  
40                  1         40  

[5 rows x 133 columns]

In [379]:
tr.describe()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  41.000000  41.000000             41.000000            41.000000   
mean    0.146341   0.170732              0.024390             0.048780   
std     0.357839   0.380949              0.156174             0.218085   
min     0.000000   0.000000              0.000000             0.000000   
25%     0.000000   0.000000              0.000000             0.000000   
50%     0.000000   0.000000              0.000000             0.000000   
75%     0.000000   0.000000              0.000000             0.000000   
max     1.000000   1.000000              1.000000             1.000000   

       shivering     chills  joint_pain  stomach_pain    acidity  \
count  41.000000  41.000000   41.000000     41.000000  41.000000   
mean    0.024390   0.170732    0.146341      0.048780   0.048780   
std     0.156174   0.380949    0.357839      0.218085   0.218085   
min     0.000000   0.000000    0.000000      0.000000   0.000000   
25%     0.000000   0.000000    0.000000      0.000000   0.000000   
50%     0.000000   0.000000    0.000000      0.000000   0.000000   
75%     0.000000   0.000000    0.000000      0.000000   0.000000   
max     1.000000   1.000000    1.000000      1.000000   1.000000   

       ulcers_on_tongue  ...  blackheads   scurring  skin_peeling  \
count         41.000000  ...   41.000000  41.000000     41.000000   
mean           0.024390  ...    0.024390   0.024390      0.024390   
std            0.156174  ...    0.156174   0.156174      0.156174   
min            0.000000  ...    0.000000   0.000000      0.000000   
25%            0.000000  ...    0.000000   0.000000      0.000000   
50%            0.000000  ...    0.000000   0.000000      0.000000   
75%            0.000000  ...    0.000000   0.000000      0.000000   
max            1.000000  ...    1.000000   1.000000      1.000000   

       silver_like_dusting  small_dents_in_nails  inflammatory_nails  \
count            41.000000             41.000000           41.000000   
mean              0.024390              0.024390            0.024390   
std               0.156174              0.156174            0.156174   
min               0.000000              0.000000            0.000000   
25%               0.000000              0.000000            0.000000   
50%               0.000000              0.000000            0.000000   
75%               0.000000              0.000000            0.000000   
max               1.000000              1.000000            1.000000   

         blister  red_sore_around_nose  yellow_crust_ooze  prognosis  
count  41.000000             41.000000          41.000000  41.000000  
mean    0.024390              0.024390           0.024390  20.000000  
std     0.156174              0.156174           0.156174  11.979149  
min     0.000000              0.000000           0.000000   0.000000  
25%     0.000000              0.000000           0.000000  10.000000  
50%     0.000000              0.000000           0.000000  20.000000  
75%     0.000000              0.000000           0.000000  30.000000  
max     1.000000              1.000000           1.000000  40.000000  

[8 rows x 133 columns]

In [380]:
tr.isnull().values.any()

False

In [381]:
x=tr.iloc[:,:-1].values  
print(x)

[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 1 1 1]]


In [382]:
tr.shape

(41, 133)

In [383]:
tr.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [384]:
X_test= tr[l1]
y_test = tr[["prognosis"]]
np.ravel(y_test)
print(X_test)
print(y_test)

    back_pain  constipation  abdominal_pain  diarrhoea  mild_fever  \
0           0             0               0          0           0   
1           0             0               0          0           0   
2           0             0               0          0           0   
3           0             0               1          0           0   
4           0             0               0          0           0   
5           0             0               1          0           0   
6           0             0               0          0           0   
7           0             0               0          0           0   
8           0             0               0          1           0   
9           0             0               0          0           0   
10          0             0               0          0           0   
11          0             0               0          0           0   
12          1             0               0          0           0   
13          0       

In [385]:
def selectsymptoms(sym1,sym2,sym3,sym4,sym5):
    x = [sym1,sym2,sym3,sym4,sym5]#storing input symptoms in y
    y = [0,0,0,0,0]#creating and giving values to the input symptoms
    if(sym1!='Select Here'):
        y[0]=1
    if(sym2!='Select Here'):
        y[1]=1
    if(sym3!='Select Here'):
        y[2]=1
    if(sym4!='Select Here'):
        y[3]=1
    if(sym5!='Select Here'):
        y[4]=1
    print(x)
    print(y)
    


In [386]:
root = Tk()
pred1=StringVar()
def DecisionTree():
    if len(NameEn.get()) == 0:
        pred1.set(" ")
        comp=messagebox.askokcancel("System","Kindly Fill the Name")
        if comp:
            root.mainloop()
    elif((Symptom1.get()=="Select Here") or (Symptom2.get()=="Select Here")):
        pred1.set(" ")
        sym=messagebox.askokcancel("System","Kindly Fill atleast first two Symptoms")
        if sym:
            root.mainloop()
    else:
        print(NameEn.get())
        from sklearn import tree

        clf3 = tree.DecisionTreeClassifier() 
        clf3 = clf3.fit(X,y)

        from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
        y_pred=clf3.predict(X_test)
        print("Decision Tree")
        print("Accuracy")
        print(accuracy_score(y_test, y_pred))
        print(accuracy_score(y_test, y_pred,normalize=False))
        print("Confusion matrix")
        conf_matrix=confusion_matrix(y_test,y_pred)
        print(conf_matrix)

        psymptoms = [Symptom1.get(),Symptom2.get(),Symptom3.get(),Symptom4.get(),Symptom5.get()]

        for k in range(0,len(l1)):
            for z in psymptoms:
                if(z==l1[k]):
                    l2[k]=1

        inputtest = [l2]
        predict = clf3.predict(inputtest)
        predicted=predict[0]
        

        h='no'
        for a in range(0,len(disease)):
            if(predicted == a):
                h='yes'
                break

    
        if (h=='yes'):
            pred1.set(" ")
            pred1.set(disease[a])
        else:
            pred1.set(" ")
            pred1.set("Not Found")
        print("Disease predicted:",disease[a])
        
        
        

            
        if(disease[a]=="Drug Reaction"):
            messagebox.showinfo("Remedies","Disease:Drug Reaction\n1.stop irritation\n2.consult nearest hospital\n3.stop taking drug\n4.follow up")
        if(disease[a]=="Malaria"):
            messagebox.showinfo("Remedies","Disease:Malaria\n1.Consult nearest hospital\n2.avoid oily food\n3.avoid non veg food\n4.keep mosquitos out")
        if(disease[a]=="Allergy"):
            messagebox.showinfo("Remedies","Disease:Allergy\n1.apply calamine\n2.cover area with bandage\n3.use ice to compress itching")
        if(disease[a]=="Hypothyroidism"):
            messagebox.showinfo("Remedies","Disease:Hypothyroidism\n1.reduce stress\n2.exercise\n3.eat healthy\n4.get proper sleep")
        if(disease[a]=="Psoriasis"):
            messagebox.showinfo("Remedies","Disease:Psoriasis\n1.wash hands with warm soapy water\n2.stop bleeding using pressure\n3.consult doctor\n4.salt baths")
        if(disease[a]=="GERD"):
            messagebox.showinfo("Remedies","Disease:GERD\n1.avoid fatty spicy food\n2.avoid lying down after eating\n3.maintain healthy weight\n4.exercise")
        if(disease[a]=="Chronic cholestasis"):
            messagebox.showinfo("Remedies","Disease:Chronic cholestasis\n1.cold baths\n2.anti itch medicine\n3.consult doctor\n4.eat healthy")
        if(disease[a]=="hepatitis A"):
            messagebox.showinfo("Remedies","Disease:hepatitis A\n1.Consult nearest hospital\n2.wash hands through\n3.avoid fatty spicy food\n4.medication")
        if(disease[a]=="Osteoarthristis"):
            messagebox.showinfo("Remedies","Disease:Osteoarthristis\n1.acetaminophen\n2.consult nearest hospital\n3.follow up\n4.salt baths")
        if(disease[a]=="(vertigo) Paroymsal  Positional Vertigo"):
            messagebox.showinfo("Remedies","Disease:(vertigo) Paroymsal Positional Vertigo\n1.lie down\n2.avoid sudden change in body\n3.avoid abrupt head movment\n4.relax")       
        if(disease[a] =="Hypoglycemia"):
            messagebox.showinfo("Remedies","Disease:Hypoglycemia\n1.lie down on side\n2.check in pulse\n3.drink sugary drinks\n4.consult doctor")
        
        
        
        
        if(disease[a] =="Acne"):          
            messagebox.showinfo("Remedies","Disease:Acne\n1.bath twice\n2.avoid fatty spicy food\n3.drink plenty of water\n4.avoid too many products")
        if(disease[a] =="Diabetes"):
            messagebox.showinfo("Remedies","Disease:Diabetes\n1.have balanced diet\n2.exercise\n3.consult doctor\n4.follow up")
        if(disease[a] =="Impetigo"):
            messagebox.showinfo("Remedies","Disease:Impetigo\n1.soak affected area in warm water\n2.use antibiotics\n3.remove scabs with wet compressed cloth\n4.consult doctor")
        if(disease[a] =="Hypertension"):
            messagebox.showinfo("Remedies","Disease:Hypertension\n1.meditation\n2.salt baths\n3.reduce stress\n4.get proper sleep")
        if(disease[a] =="Peptic ulcer diseae"):
            messagebox.showinfo("Remedies","Disease:Peptic ulcer diseae\n1.avoid fatty spicy food\n2.consume probiotic food\n3.eliminate milk\n4.limit alcohol")
        if(disease[a] =="Dimorphic hemmorhoids(piles)"):
            messagebox.showinfo("Remedies","Disease:Dimorphic hemmorhoids(piles)\n1.avoid fatty spicy food\n2.consume witch hazel\n3.warm bath with epsom salt\n4.consume alovera juice")
        if(disease[a] =="Common Cold"):
            messagebox.showinfo("Remedies","Disease:Common Cold\n1.drink vitamin c rich drinks\n2.take vapour\n3.avoid cold food\n4.keep fever in check")
        if(disease[a] =="Chicken pox"):
            messagebox.showinfo("Remedies","Disease:Chicken pox\n1.use neem in bathing\n2.consume neem leaves\n3.take vaccine\n4.avoid public places")
        if(disease[a] =="Migraine"):
            messagebox.showinfo("Remedies","Disease:Migraine\n1.Avoid loud noises and bright lights\n2.Pay attention to food choices\n3.Keep a headache diary\n4.Beware of hormonal changes")
        
        if(disease[a]=="Cervical spondylosis"):
            messagebox.showinfo("Remedies","Disease:Cervical spondylosis\n1.use heating pad or cold pack\n2.exercise\n3.take otc pain reliver\n4.consult doctor")
        if(disease[a]=="Hyperthyroidism"):
            messagebox.showinfo("Remedies","Disease:Hyperthyroidism\n1.eat healthy\n2.massage\n3.use lemon balm\n4.take radioactive iodine treatment")
        if(disease[a]=="Urinary tract infection"):
            messagebox.showinfo("Remedies","Disease:Urinary tract infection\n1.drink plenty of water\n2.increase vitamin c intake\n3.drink cranberry juice\n4.take probiotics")
        if(disease[a]=="Varicoseveins"):    
            messagebox.showinfo("Remedies","Disease:Varicose veins\n1.lie down flat and raise the leg high\n2.use oinments\n3.use vein compression\n4.dont stand still for long")
        if(disease[a]=="AIDS"):
            messagebox.showinfo("Remedies","Disease:AIDS\n1.avoid open cuts\n2.wear ppe if possible\n3.consult doctor\n4.follow up")
        if(disease[a]=="Paralysis (brain hemorrhage)"):    
            messagebox.showinfo("Remedies","Disease:Paralysis\n1.massage\n2.eat healthy\n3.exercise\n4.consult doctor")
        if(disease[a]=="Typhoid"):    
            messagebox.showinfo("Remedies","Disease:Typhoid\n1.eat high calorie vegitables\n2.antiboitic therapy\n3.Avoid meat&fatty food\n4.consult doctor")
        if(disease[a]=="Hepatitis B"):    
            messagebox.showinfo("Remedies","Disease:Hepatitis B\n1.Consult nearest hospital\n2.vaccination\n3.eat healthy\n4.consult doctor")
        if(disease[a]=="Fungal infection"):    
            messagebox.showinfo("Remedies","Disease:Fungal infection\n1.bath twice\n2.use detol or neem in bathing water\n3.keep infected area dry\n4.consult doctor")
        if(disease[a]=="Hepatitis C"):    
            messagebox.showinfo("Remedies","Disease:Hepatitis C\n1.Consult nearest hospital\n2.vaccination\n3.eat healthy\n4.consult doctor") 
        if(disease[a] =="Bronchial Asthma"):
            messagebox.showinfo("Remedies","Disease:Bronchial Asthma\n1.switch to loose clothing\n2.take deep breaths\n3.get away from trigger\n4.seek help")
        if(disease[a] =="Alcoholic hepatitis"):
            messagebox.showinfo("Remedies","Disease:Alcoholic hepatitis\n1.stop alcohol consumption\n2.consult doctor\n3.medication\n4.follow up")
        if(disease[a] =="Jaundice"):
            messagebox.showinfo("Remedies","Disease:Jaundice\n1.drink plenty of water\n2.consume milk thistle\n3.eat fruits and high fiberous food\n4.medication")
        if(disease[a] =="Hepatitis E"):
            messagebox.showinfo("Remedies","Disease:Hepatitis E\n1.stop alcohol consumption\n2.rest\n3.consult doctor\n4.medication")
        if(disease[a] =="Dengue"):
            messagebox.showinfo("Remedies","Disease:Dengue\n1.drink papaya leaf juice\n2.avoid fatty spicy food\n3.keep mosquitoes away\n4.keep hydrated")
        if(disease[a] =="Hepatitis D"):
            messagebox.showinfo("Remedies","Disease:Hepatitis D\n1.consult doctor\n2.medication\n3.keep healthy\n4.follow up")
        if(disease[a] =="Heartattack"):
            messagebox.showinfo("Remedies","Disease:Heart attack\n1.call ambulance\n2.chewor swallow asprin\n3.keep calm")
        if(disease[a] =="Pneumonia"):
            messagebox.showinfo("Remedies","Disease:Pneumonia\n1.consult doctor\n2.medication\n3.rest\n4.follow up")
        if(disease[a] =="Arthritis"):
            messagebox.showinfo("Remedies","Disease:Arthritis\n1.exercise\n2.use hot and cold therapy\n3.try acupuncture\n4.massage")
        if(disease[a] =="Gastroenteritis"):
            messagebox.showinfo("Remedies","Disease:Gastroenteritis\n1.stop eating solid food for while\n2.try taking small sips of water\n3.rest\n4.ease back into eating")
        if(disease[a] =="Tuberculosis"):
            messagebox.showinfo("Remedies","Disease:Tuberculosis\n1.cover mouth\n2.consult doctor\n3.medication\n4.rest")
        
        selectsymptoms(Symptom1.get(),Symptom2.get(),Symptom3.get(),Symptom4.get(),Symptom5.get())

In [387]:
root.configure(background='#ccffff')
root.title('Disease Predictor System')
root.resizable(0,0)

''

In [388]:
#taking first input as symptom
Symptom1 = StringVar()
Symptom1.set("Select Here")

#taking second input as symptom
Symptom2 = StringVar()
Symptom2.set("Select Here")

#taking third input as symptom
Symptom3 = StringVar()
Symptom3.set("Select Here")

#taking fourth input as symptom
Symptom4 = StringVar()
Symptom4.set("Select Here")

#taking fifth input as symptom
Symptom5 = StringVar()
Symptom5.set("Select Here")
Name = StringVar()

In [389]:
prev_win=None
def Reset():
    global prev_win

    Symptom1.set("Select Here")
    Symptom2.set("Select Here")
    Symptom3.set("Select Here")
    Symptom4.set("Select Here")
    Symptom5.set("Select Here")
    
    NameEn.delete(first=0,last=100)
    
    pred1.set(" ")
    pred2.set(" ")
    pred3.set(" ")
    pred4.set(" ")
    try:
        prev_win.destroy()
        prev_win=None
    except AttributeError:
        pass

In [390]:
from tkinter import messagebox
def Exit():
    qExit=messagebox.askyesno("System","Do you want to exit the system")
    if qExit:
        root.destroy()
        exit()

In [391]:
w2 = Label(root, justify=LEFT, text="Disease Prediction Using Symptoms", fg="#ff0066", bg="#ccffff")
w2.config(font=("Times",30,"bold"))
w2.grid(row=1, column=0, columnspan=5, padx=100)

In [392]:
NameLb = Label(root, text="Name of the Patient", fg="#ff3300", bg="#ccffff")
NameLb.config(font=("Times",15,"bold italic"))
NameLb.grid(row=6, column=0, pady=15, sticky=W)

In [393]:
S1Lb = Label(root, text="Symptom 1", fg="Black", bg="#ccffff")
S1Lb.config(font=("Times",15,"bold italic"))
S1Lb.grid(row=7, column=0, pady=10, sticky=W)

S2Lb = Label(root, text="Symptom 2", fg="Black", bg="#ccffff")
S2Lb.config(font=("Times",15,"bold italic"))
S2Lb.grid(row=8, column=0, pady=10, sticky=W)

S3Lb = Label(root, text="Symptom 3", fg="Black",bg="#ccffff")
S3Lb.config(font=("Times",15,"bold italic"))
S3Lb.grid(row=9, column=0, pady=10, sticky=W)

S4Lb = Label(root, text="Symptom 4", fg="Black", bg="#ccffff")
S4Lb.config(font=("Times",15,"bold italic"))
S4Lb.grid(row=10, column=0, pady=10, sticky=W)

S5Lb = Label(root, text="Symptom 5", fg="Black", bg="#ccffff")
S5Lb.config(font=("Times",15,"bold italic"))
S5Lb.grid(row=11, column=0, pady=10, sticky=W)


In [394]:
OPTIONS = sorted(l1)

In [395]:
NameEn = Entry(root, textvariable=Name)
NameEn.grid(row=6, column=1)

S1 = OptionMenu(root, Symptom1,*OPTIONS)
S1.grid(row=7, column=1)

S2 = OptionMenu(root, Symptom2,*OPTIONS)
S2.grid(row=8, column=1)

S3 = OptionMenu(root, Symptom3,*OPTIONS)
S3.grid(row=9, column=1)

S4 = OptionMenu(root, Symptom4,*OPTIONS)
S4.grid(row=10, column=1)

S5 = OptionMenu(root, Symptom5,*OPTIONS)
S5.grid(row=11, column=1)

In [396]:
dst = Button(root, text="Prediction", command=DecisionTree,bg="#003366",fg="white")
dst.config(font=("Times",15,"bold italic"))
dst.grid(row=6, column=3,padx=10)

rs = Button(root,text="Reset Inputs", command=Reset,bg="#003366",fg="white",width=15)
rs.config(font=("Times",15,"bold italic"))
rs.grid(row=10,column=3,padx=10)

ex = Button(root,text="Exit System", command=Exit,bg="#003366",fg="white",width=15)
ex.config(font=("Times",15,"bold italic"))
ex.grid(row=11,column=3,padx=10)

In [397]:
t1=Label(root,font=("Times",15,"bold italic"),text="Decision Tree",height=1,bg="white"
         ,width=40,fg="red",textvariable=pred1,relief="sunken").grid(row=15, column=1, padx=10)

In [398]:
root.mainloop()

jj
Decision Tree
Accuracy
0.9512195121951219
39
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Disease predicted: Diabetes
['constipation', 'hip_joint_pain', 'increased_appetite', 'Select Here', 'Select Here']
[1, 1, 1, 0, 0]
